// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/deep-equal/index.d.ts
declare module 'deep-equal' {
// Type definitions for deep-equal
// Project: https://github.com/substack/node-deep-equal
// Definitions by: remojansen <https://github.com/remojansen>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped



interface DeepEqualOptions {
    strict: boolean;
}

let deepEqual: (
    actual: Object,
    expected: Object,
    opts?: DeepEqualOptions) => boolean;

export = deepEqual;
}
